CREATE TABLE ACCOUNT (
    ID VARCHAR(64) NOT NULL,
    NAME VARCHAR(128) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE GAME (
    ID VARCHAR(64) NOT NULL,
    CREATE_TIME TIMESTAMP NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE BUY_IN (
    ID VARCHAR(64) NOT NULL,
    GAME_ID VARCHAR(64) NOT NULL,
    ACCOUNT_ID VARCHAR(64) NOT NULL,
    AMOUNT NUMERIC(20, 6) NOT NULL,
    CREATE_TIME TIMESTAMP NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (GAME_ID) REFERENCES GAME(ID),
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ID)
);

CREATE TABLE CASH_OUT (
    ID VARCHAR(64) NOT NULL,
    GAME_ID VARCHAR(64) NOT NULL,
    ACCOUNT_ID VARCHAR(64) NOT NULL,
    AMOUNT NUMERIC(20, 6) NOT NULL,
    CREATE_TIME TIMESTAMP NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (GAME_ID) REFERENCES GAME(ID),
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ID)
);

CREATE TABLE PAYMENT (
    ID VARCHAR(64) NOT NULL,
    GAME_ID VARCHAR(64) NOT NULL,
    ACCOUNT_ID VARCHAR(64) NOT NULL,
    AMOUNT NUMERIC(20, 6) NOT NULL,
    SIDE VARCHAR(32) NOT NULL,
    CREATE_TIME TIMESTAMP NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (GAME_ID) REFERENCES GAME(ID),
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ID)
);