CREATE TABLE ACCOUNT (
    ID CHAR(64) NOT NULL,
    NAME VARCHAR(128) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE GAME (
    ID CHAR(64) NOT NULL,
    CREATE_TIME TIMESTAMP NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE BUY_IN (
    ID CHAR(64) NOT NULL,
    GAME_ID CHAR(64) NOT NULL,
    ACCOUNT_ID CHAR(64) NOT NULL,
    AMOUNT NUMERIC(20, 6) NOT NULL,
    CREATE_TIME TIMESTAMP NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (GAME_ID) REFERENCES GAME(ID),
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ID)
);